### ISSUE TITLE
One-time auth?

### ISSUE THREAD

**Issue by limejet** [uditkarode/Minegram#3]
Hi, big fan of this tool, it works great!

I'm wondering about the `/auth` command. I run a private server that is linked to a private telegram group so authing every time feels redundant. Is it possible to bypass it in some way? If, for example, `/link <username>` just added the user in question to the server whitelist, it intuitively feels like `/auth` wouldn't be required, and it would just plain prevent people from joining rather than having to blind and move them.

For my use case, having the bot also keep track of which linked accounts that are still in the group and unlinking them if they leave would also be helpful, but i know that there's no way for bots to see channel members so that would require more effort.

**Comment by uditkarode** [comment]
Hello!

Auth being required everytime was originally intended for offline-mode servers, since in that case anyone can join the server with your IGN when you're offline.

I can, however, add a mode that just kicks players that haven't `/link`ed on Telegram first, and remove the need for `/auth` if they have.

**Comment by limejet** [comment]
I see, that use case hadn't even occurred to me. I can see how it's useful if there's no external auth available. I'd love it if that mode was added! It would also solve a different problem for me, namely that the gamemode people are returned to after authenticating is always (?) survival, which has caused me to fall out of the sky more than once :)

**Comment by uditkarode** [comment]
Finally got around to this!
Are you able to build and test if it works fine for your use-case?\
The new mode can be set like:
`auth_enabled = link_only`

![image](https://github.com/uditkarode/Minegram/assets/30829387/2d6e730b-e045-4e67-9e02-10fb1f8bcdef)

**Comment by limejet** [comment]
Once I actually got it to build properly, yes! This mode works exactly how I envisioned.

About that, you should probably update the build instructions to statically link sqlite:

```shell
git clone https://github.com/uditkarode/Minegram.git
cd Minegram
go get -u
export CGO_ENABLED=1
go build -ldflags "-linkmode external -extldflags -static"
```

That way you're not dependent on all libraries living in the same location on other machines. I got an error because i built it in an alpine linux based docker image. Alternatively, have gorm use [glebarez/sqlite](https://github.com/glebarez/sqlite) and you're rid of the C dependency.

**Comment by uditkarode** [comment]
Nice to know it works as expected!

Also thanks for the suggestion. Getting rid of the C dependency does sound like a good idea. I'll look into it and update the README soon enough. Will also close this issue once that's done, but feel free to re-open if anything relevant breaks.
